name: lifx_http_api
description: A dart implementation of the LIFX HTTP API for smart LED bulbs.
version: 0.0.15
homepage: https://github.com/nathanielgreen/lifx_http_api
repository: https://github.com/nathanielgreen/lifx_http_api

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  cli_repl: ^0.2.3
  dotenv: ^4.0.1
  http: ^0.13.5
  json_annotation: ^4.6.0

dev_dependencies:
  json_serializable: ^6.3.2
  lints: ^2.0.0
  build_runner: ^2.2.1

